### ISSUE TITLE
I/flutter (32447): Error parsing .msg file with flutter_msg_parser: RangeError (byteOffset): Index out of range: index should be less than 149: 150

### ISSUE THREAD

**Issue by Zakriahassan44** [dickverweij/flutter_msg_parser#1]
Hi sir i am trying to view msg file using your api . but its not working please tell me about how to fix it

**Comment by dickverweij** [comment]
Hi @Zakriahassan44, Could you provide me with a stack trace of the error en possible a MSG file for which you have this error?
